### ISSUE TITLE
--python does not work with poetry 1.5.0

### ISSUE THREAD

**Issue by fyhertz** [python-poetry/poetry-plugin-bundle#58]
In addition to issue https://github.com/python-poetry/poetry-plugin-bundle/issues/55, this plugin fails when used with poetry 1.5.0 and with `--python`:

```
    AttributeError

    'str' object has no attribute 'resolve'

    at ~/work/wakemeops/blueprints/dev/poetry/output/poetry_1.5.0_amd64/fetched/bootstrap/lib/python3.11/site-packages/poetry/utils/env.py:1082 in build_venv
        1078│             if with_wheel is not None
        1079│             else flags.pop("no-wheel", flags["no-pip"])
        1080│         )
        1081│
      → 1082│         executable_str = None if executable is None else executable.resolve().as_posix()
        1083│
        1084│         args = [
        1085│             "--no-download",
        1086│             "--no-periodic-update",
```
